azure:
  subscriptionID: 81dde535-61b4-442a-96e6-6e30c6e55039
  tenantID: e9ec4533-d130-4d00-a7c3-d85f1c750c5a
  region: westeurope
  countUpdateDomains: 5
  countFaultDomains: 2

create:
  vnet: true
  availabilitySet: false

clusterName: shoot--test--azure

vnet:
  name: my-vnet
  # resourceGroup: vnet-resource-group
  cidr: 10.250.0.0/16
  subnet:
    cidr: 10.250.0.0/19
    serviceEndpoints: []

outputKeys:
  resourceGroupName: resourceGroupName
  vnetName: vnetName
  # vnetResourceGroup: vnet-resource-group
  subnetName: subnetName
  availabilitySetID: availabilitySetID
  availabilitySetName: availabilitySetName
  routeTableName: routeTableName
  securityGroupName: securityGroupName
